### ISSUE TITLE
[Bug] Abnormal termination. like ANR

### ISSUE THREAD

**Issue by jaeyunn15** [Groovee60/ExoPlayerServiceExample#2]
Hello. 
I think your example is highly complete code.
But I found a problem in your code.

It might just happen to me.(Hmm..)
The application does not respond very frequently.
Screenshot below.
<image src="https://user-images.githubusercontent.com/55985789/105623597-57542080-5e5e-11eb-89f8-fad59db185dc.png" width="300" height="500"/>

Error logs are no longer helpful. 😂

**Comment by jaeyunn15** [comment]
@Groovee60

**Comment by Groovee60** [comment]
Hello, I have also seen this but only when running on my slower tablet device. Both here in this sample app and in my larger scale music app that utilizes the same service architecture. I have upgraded some dependencies, including the ExoPlayer library (with changes to how the player view is integrated) and made some other optimizations. 

Unfortunately, I still see the ANR failure (which is annoying but does not otherwise fail), but much more rarely. Further debugging has not discovered anything and it does seem to be happening completely within the library and not my code but of course I can't be certain.

I will make the same updates in my music app and continue to debug it, bringing any further changes back to this sample code. Appreciate you corroborating the issue and providing any further info, including pull requests, that you can. 

Thanks.

**Comment by Groovee60** [comment]
@jaeyunn15 Hello again - this should be fixed now. It was an issue with how the foreground service and notifications are handled on Android 10 and above.  As enormous and complicated as it is, the ExoPlayer samples on GitHub do NOT address this issue, so this sample project is even more important now.  

I have integrated the same changes into my full-scale music app that was experiencing the same problem on a tablet running Android 10, and I know longer see any failures. But please let me know if you still see any problems. Thank you.

**Comment by Groovee60** [comment]
Fixed Android 10-specific issue with foreground service and notifications management.
